# -- 코드를 입력하세요
SELECT
    AUTHOR_ID,
    (SELECT AUTHOR_NAME FROM AUTHOR a WHERE b.AUTHOR_ID = a.AUTHOR_ID) AS AUTHOR_NAME,
    CATEGORY,
    SUM(PRICE * SALES) AS TOTAL_SALES
FROM
    BOOK b
    RIGHT JOIN
    BOOK_SALES bs
    ON b.BOOK_ID = bs.BOOK_ID
WHERE
    LEFT(bs.SALES_DATE, 7) = '2022-01'
GROUP BY
    AUTHOR_ID,
    CATEGORY
ORDER BY
    AUTHOR_ID,
    CATEGORY DESC
    