-- 코드를 입력하세요

SELECT 
    g.PRODUCT_CODE,
    SUM(g.SALE) AS SALES
FROM (
    SELECT p.PRODUCT_ID, (os.SALES_AMOUNT * p.PRICE) AS SALE, p.PRODUCT_CODE 
    FROM
        PRODUCT p INNER JOIN OFFLINE_SALE os
        ON p.PRODUCT_ID = os.PRODUCT_ID
) g
GROUP BY g.PRODUCT_CODE
ORDER BY SUM(g.SALE) DESC, g.PRODUCT_CODE ASC
