
SELECT
    COUNT(fi.FISH_TYPE) AS FISH_COUNT,
    (SELECT FISH_NAME
     FROM FISH_NAME_INFO fni
     WHERE fni.FISH_TYPE = fi.FISH_TYPE) AS FISH_NAME
FROM 
    FISH_INFO fi
GROUP BY
    fi.FISH_TYPE
ORDER BY
    COUNT(fi.FISH_TYPE) DESC
