-- 코드를 입력하세요
SELECT
    fp.PRODUCT_ID,
    (SELECT f.PRODUCT_NAME
     FROM FOOD_PRODUCT f 
     WHERE f.PRODUCT_ID = fp.PRODUCT_ID) AS PRODUDCT_NAME,
    SUM(fp.PRICE * fo.AMOUNT) AS TOTAL_SALES
FROM 
    FOOD_PRODUCT fp INNER JOIN FOOD_ORDER fo
    ON fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE 
    YEAR(fo.PRODUCE_DATE) = 2022 AND
    MONTH(fo.PRODUCE_DATE) = 5
GROUP BY 
    fp.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC,
    PRODUCT_ID ASC
    