-- 코드를 입력하세요
SELECT
    (SELECT MEMBER_NAME
    FROM MEMBER_PROFILE mp
    WHERE mp.MEMBER_ID=rr.MEMBER_ID) AS MEMBER_NAME,
    REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM 
    REST_REVIEW rr
WHERE
    MEMBER_ID = (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(REVIEW_ID) DESC
        LIMIT 1
    )
ORDER BY
    REVIEW_DATE,
    REVIEW_TEXT