WITH ECOLI AS (
    SELECT ID, PARENT_ID, GENOTYPE
    FROM ECOLI_DATA
)
SELECT
    c.ID,
    c.GENOTYPE,
    p.GENOTYPE AS PARENT_GENOTYPE
FROM
    ECOLI p
JOIN
    ECOLI c ON p.ID = c.PARENT_ID
WHERE
    p.GENOTYPE & c.GENOTYPE = p.GENOTYPE
ORDER BY
    c.ID