-- 코드를 작성해주세요
SELECT
    YEAR(e.DIFFERENTIATION_DATE) AS YEAR,
    me.MAXIMUM - e.SIZE_OF_COLONY AS YEAR_DEV,
    e.ID
FROM
    ECOLI_DATA e
    LEFT JOIN
    (SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAXIMUM
    FROM ECOLI_DATA
    GROUP BY YEAR) me ON YEAR(e.DIFFERENTIATION_DATE) = me.YEAR
ORDER BY
    YEAR,
    YEAR_DEV